### ISSUE TITLE
Installation of MultiMAP dependencies

### ISSUE THREAD

**Issue by 5rycaa** [Teichlab/MultiMAP#2]
Hi!

I am trying to setup conda environment to run your software, which means that there are extra packages that were needed to install. Eg. pandas, packaging, importlib.metadata...

But while I could pass over those, I am getting stuck installing anndata due to AttributeError: module ‘anndata’ has no attribute ‘logging’.

I am assuming it might be problem with the version of anndata as in recent versions certain structures have been changed. Could you help me by telling which version are you using? Even better, could you list all the packages and dependencies connected to MultiMAP?

Thanks a lot!

**Comment by ktpolanski** [comment]
`anndata` is not a formal MultiMAP dependency as it is possible to run `MultiMAP.matrix.MultiMAP()` without it. I've ran MultiMAP locally on a machine with `anndata==0.7.5` (and `scanpy==1.6.0`).

**Comment by 5rycaa** [comment]
Perfect, thanks a lot!
